# Generated by Django 5.1 on 2024-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='pincode',
            field=models.CharField(default='632007', max_length=7, verbose_name='Pincode'),
        ),
    ]
