# Generated by Django 5.1 on 2024-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0002_venue_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(default='', upload_to='media/venue/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='pincode',
            field=models.CharField(default='63200', max_length=7, verbose_name='Pincode'),
        ),
    ]
